server.port=8080

# ?? ??
# mysql config
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# mybatis config
mybatis.mapper-locations=classpath:com.ccommit.fashionserver.mapper/*.xml

# ?? ????? ???? ?? ??
spring.profiles.active=local